### ISSUE TITLE
Repetición de código en plantillas jade

### ISSUE THREAD

**Issue by JJ** [oslugr/ugr-transparente-servidor#1]
Las plantillas son casi idénticas, por ejemplo, leytransparencia.jade y alumnos.jade De 130 líneas tienen más de 100 comunes. jade es bastante flexible y se pueden hacer esas cosas en una sola plantilla o bien crear una plantilla que descienda de layout y dejar sólo como plantillas secundarias. Por favor, mira la forma de hacerlo. Cuando hay repetición de código, y mucho más cuando es una plantilla, es que hay algún error. Imagínate que tienes que cambiar algo, tendrías que hacerlo en 10 plantillas.

**Comment by oslugr** [comment]
Reabro y reasigno
