### ISSUE TITLE
Tests de cobertura

### ISSUE THREAD

**Issue by JJ** [oslugr/ugr-transparente-servidor#10]
Ahora mismo  hay un par de tests que no cubren prácticamente nada. Habría que pasar una herramienta que viera la cobertura, se puede hacer con mocha o con espresso http://stackoverflow.com/questions/4308786/what-is-the-best-testing-framework-to-use-with-node-js.

**Comment by germaaan** [comment]
Cerrado con e6e8a1bc763ac5b18e73b9b6c05c42bdeda9bf6a
