### ISSUE TITLE
Add a contributing guidelines

### ISSUE THREAD

**Issue by demiurgosoft** [oslugr/ugr-transparente-servidor#104]
using CONTRIBUTE.ms (<https://github.com/blog/1184-contributing-guidelines>)

**Comment by JJ** [comment]
Great!

2016-03-14 19:47 GMT+01:00 Andrés <notifications@github.com>:

> using CONTRIBUTE.ms (https://github.com/blog/1184-contributing-guidelines)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/104>.
>



-- 
JJ
