### ISSUE TITLE
Escribir nuevos tests

### ISSUE THREAD

**Issue by JJ** [oslugr/ugr-transparente-servidor#11]
Una vez visto en #10 qué test faltan (casi todos), escribir todos los que hagan falta al menos de la parte crítica, el acceso a los datos.

**Comment by germaaan** [comment]
He hecho los test que comprueban que existen los JSONs de los que se cargan los datos y que están bien formados (tiene el número de campos correspondientes, los nombres de los campos son los correctos, los valores que tienen que ser un valor en concreto sea esa valor en concreto para que no de problema a la hora de que los procese Jade) y que se haga un request de acceso a cada una de las páginas para comprobar que son accesibles vía web.

Al margen de lo mismo individualizar los test y por ejemplo lanzarlos con un make (que he visto muchos ejemplos de ese estilo) y hacer que el propio mocha genere una página de resultados accesible desde el navegador para que no tenga que ejecutarse desde terminal. ¿Alguna idea de test más?

**Comment by JJ** [comment]
Los tests unitarios deben cubrir todas las funcionalidades. Puedes pasarle
un test de cobertura a ver cuáles lo están

El 27 de marzo de 2015, 12:54, German Martinez <notifications@github.com>
escribió:

> He hecho los test que comprueban que existen los JSONs de los que se
> cargan los datos y que están bien formados (tiene el número de campos
> correspondientes, los nombres de los campos son los correctos, los valores
> que tienen que ser un valor en concreto sea esa valor en concreto para que
> no de problema a la hora de que los procese Jade) y que se haga un request
> de acceso a cada una de las páginas para comprobar que son accesibles vía
> web.
>
> Al margen de lo mismo individualizar los test y por ejemplo lanzarlos con
> un make (que he visto muchos ejemplos de ese estilo) y hacer que el propio
> mocha genere una página de resultados accesible desde el navegador para que
> no tenga que ejecutarse desde terminal. ¿Alguna idea de test más?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/11#issuecomment-86912137>
> .
>



-- 
JJ

**Comment by germaaan** [comment]
Cerrado con e6e8a1bc763ac5b18e73b9b6c05c42bdeda9bf6a
