### ISSUE TITLE
Cambiar motor de visualización

### ISSUE THREAD

**Issue by germaaan** [oslugr/ugr-transparente-servidor#110]
Por motivos legales el paquete "jade" ha tenido que ser renombrado como "pug": https://github.com/pugjs/pug/issues/2184

Actualizar dependencias y motor de visualización.

**Comment by germaaan** [comment]
Muchos cambios son necesarios, mirando si cambiar a otro motor. Candidatos:

* Mustache
* Handlebars
* Hogan
* EJS

**Comment by demiurgosoft** [comment]
EJS, EJS!

**Comment by germaaan** [comment]
Usando Handlebars, que permite incluir una lógica de programación mínima dentro de las plantillas similar a la de Mustache para procesar la información recibida mediante JSONs, puedo incluir otros archivos y usa HTML sin depender de la indentación, pero además permite usar bloques definidos para funcionalidades determinadas.

**Comment by demiurgosoft** [comment]
handlebars tiene pinta de estar orientado a cliente, no servidor, creo que dara problemas futuros...

**Comment by germaaan** [comment]
Todos los que heredan de Mustache (que son la mayoría) tienen un funcionamiento similar.

**Comment by demiurgosoft** [comment]
yo solo lo aviso...

**Comment by demiurgosoft** [comment]
rehaciendo todo (again) con handlebars

**Comment by demiurgosoft** [comment]
los helpers de handlebars son monstruosos, volviendo a EJS

**Comment by demiurgosoft** [comment]
Se puede precompilar ejs con gulp para tener ya los html listos directamente si fuera necesario 
https://github.com/christophehurpeau/gulp-ejs-precompiler

**Comment by iblancasa** [comment]
¿Por qué no cambiáis a pug y ya?

**Comment by germaaan** [comment]
Llevábamos algo de tiempo queriendo poder usar plantillas que no tengas que escribir un código que no es HTML para ver el HTML, sobretodo por tener que adaptarnos a los estilos CSS que tenemos que usar, pero que nos hemos desarrollado nosotros, lo que a veces se vuelve algo realmente enrevesado.

El problema es que no terminamos de encontrar ese que nos convenza del todo.

**Comment by JJ** [comment]
No digáis eso. ¿No habíamos quedado esta mañana en que se iba a usar ejs?

@iblancasa, que sepas que les he propuesto Polymer.

**Comment by germaaan** [comment]
A ver, a mi inicialmente el que me convenció fue Handlebars porque en todo lo que había leído en muchas comparativas (además de todos los sitios que me he encontrado que lo usaban, tomándolo como la evolución natural de Mustache), pero es lo que te hemos comentado esta mañana, al pasar de la teoría a la práctica es algo que se iba muy montaña para un grano de arena.

Yo no era muy fan de la idea de EJS (tampoco lo conocía mucho, solo de lo que había leído, lo que después de la experiencia con Handlebars...), es @demiurgosoft el que ha sido el gran valedor de la idea. La cuestión está en que si es algo que va a ser más mantenible y no presenta ningún problema, habrá que intentarlo al menos.

**Comment by iblancasa** [comment]
@germaaan es normal lo que os ha pasado con Jade/Pug. Hay muchos Jadeliers pero a mí no me gusta por que no sé qué estoy haciendo. EJS es de los que más me ha gustado. Sí te digo que uno que deberíais descartar sí o sí es Moustache (es sencillo de usar, pero cuando empiezas a trabajar con él, echas de menos algunas cosas a la larga).

@JJ no sería mala idea el uso de Polymer. Realmente no tiene por qué pisarse con lo que están buscando. Es decir, mediante un template engine como es EJS (por decir uno) pueden crear webcomponents basados (o no) en Polymer. Si no lo basan en Polymer, el problema es que no van a poder ejecutarse (todavía) en otros navegadores que no sean Chrome y Opera (Firefox pronto).
http://caniuse.com/#feat=custom-elements Si queréis, esperad para solucionar este issue y un día quedamos y os comento un poco sobre Polymer (pero enfocándolo a este proyecto).

No sé si conocéis esta web
https://garann.github.io/template-chooser/

**Comment by germaaan** [comment]
Ok, pues gracias por el ofrecimiento @iblancasa, que además me quedé con ganas de haber visto de que iba Polymer.

**Comment by demiurgosoft** [comment]
han pasado muchas cosas, pero ya esta funcionando con ejs

**Comment by demiurgosoft** [comment]
Test de navegabilidad funconando, esperando a aceptar pull request
