### ISSUE TITLE
Sacar más provecho al gulpfile

### ISSUE THREAD

**Issue by iblancasa** [oslugr/ugr-transparente-servidor#113]
He visto que tenéis algunas cosas por ahí desperdigadas y que podríais hacerlas en el Gulpfile.
¿Puedo echar una mano?

**Comment by JJ** [comment]
¡Claro!

2016-04-13 17:53 GMT+02:00 Israel Blancas <notifications@github.com>:

> He visto que tenéis algunas cosas por ahí desperdigadas y que podríais
> hacerlas en el Gulpfile.
> ¿Puedo echar una mano?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/113>
>



-- 
JJ

**Comment by germaaan** [comment]
El software libre sea contigo, xD
