### ISSUE TITLE
test de navegabilidad - mapa web

### ISSUE THREAD

**Issue by demiurgosoft** [oslugr/ugr-transparente-servidor#115]

**Comment by iblancasa** [comment]
¿Por qué no lo estáis ejecutando en Travis?

**Comment by demiurgosoft** [comment]
Principalmente porque comprueba links ajenos a nuestro servidor y puede dar errores ajenos al desarollo. Idealmente, sería interesante automatizar estas pruebas, testeando en el momento de ponerlo en produccion
