### ISSUE TITLE
Cambiar páginas por ajax

### ISSUE THREAD

**Issue by demiurgosoft** [oslugr/ugr-transparente-servidor#128]
Usar [instanclick](http://instantclick.io/), p-jax o alguna tecnología similar

**Comment by demiurgosoft** [comment]
instantclick est medio muerto, probando con turbolinks

**Comment by demiurgosoft** [comment]
diversos errores en los tests de navegabilidad

error al cargar pagina (no parece influir en la carga real, asi que lo he comentado)

comprobar si los errores son por turbolink o no

**Comment by JJ** [comment]
Pero ¿no ibas a crear tu propio Instantclick?

**Comment by demiurgosoft** [comment]
con casinos... 

esta el repo, vere si puedo ir trabajando en mejorarlo, mientras, con turbolinks parece que funciona

**Comment by demiurgosoft** [comment]
error en los tests de buscador (zombiejs no parece ir bien con ciertos scripts), debido a futuro cambio de buscador ( #127) no se arreglará de momento.

Probando manualmente todo funciona
