### ISSUE TITLE
Error en npm install en travis

### ISSUE THREAD

**Issue by demiurgosoft** [oslugr/ugr-transparente-servidor#157]
Travis.ci falla en la instalación:
```
npm ERR! fetch failed https://registry.npmjs.org/escape-regexp/-/escape-regexp-0.0.1.tgz
```

escape-regexp parece ser una dependencia de pm2:
```
└─┬ pm2@1.1.3
  └─┬ pm2-axon@2.0.11
    └── escape-regexp@0.0.1 
```

Npm install no parece dar errores en local

**Comment by demiurgosoft** [comment]
Confirmado, es un problema de travis+escape-regexp (algún link roto o algo raro), el mismo error pasa ejecutando un tests de master en travis que ya había pasado correctamente antes.

Por lo pronto no hay actualizaciones para arreglar esto, miraré donde se puede poner un issue de esto

**Comment by JJ** [comment]
Hoy parece que ha habido errores en npm de todas formas. Lo están poniendo
en Twitter.

**Comment by demiurgosoft** [comment]
Probablemente sea algo de eso, a ver si en unos dias se arregla

**Comment by demiurgosoft** [comment]
Parece que los tests en travis están pasando, si pasan todos cierro el issue
