### ISSUE TITLE
Incluir integración continua

### ISSUE THREAD

**Issue by germaaan** [oslugr/ugr-transparente-servidor#16]
Usar Travis para añadir integración continua a ugr-transparente-servidor.

**Comment by JJ** [comment]
Guay

**Comment by germaaan** [comment]
http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/
"Node.js 0.12.2 is available, and is now the default."

Añado también a la configuración de Travis la versión 0.12 de Node porque a partir de la próxima actualización es la que van a establecer como por defecto.

**Comment by JJ** [comment]
OK. TAmbién puedes poner io.js, creo, el fork de node.

**Comment by germaaan** [comment]
Pues ahora lo miro. Una cosa, ¿sabes por qué la build de los pull request siempre termina dando error? https://travis-ci.org/oslugr/ugr-transparente-servidor/pull_requests

**Comment by JJ** [comment]
Fallan los git fetch. El problema es que haces los pull requests de una
rama a otra. Yo creo que tenías que fusionarlos directamente desde
clientes. No tienes más que hacer git pull de la otra rama para fusionarlo.

**Comment by germaaan** [comment]
Ah vale, pues lo tendré en cuenta a partir de ahora.

**Comment by germaaan** [comment]
Integración continua para Node.js 0.10, 0.11 y 0.12 y io.js funcionando: https://travis-ci.org/oslugr/ugr-transparente-servidor/builds/59862546
