### ISSUE TITLE
Obtener datos de forma automática

### ISSUE THREAD

**Issue by mariohm** [oslugr/ugr-transparente-servidor#21]
Usar API de CKAN para traer los conjuntos de datos con sus tablas de Open Data:

http://opendata.ugr.es/api/3/action/package_search?q=administracion -> Esta dirección nos devuelve un JSON con todos los conjuntos de datos que se encuentran en el grupo Administración.

http://opendata.ugr.es/api/3/action/package_show?id=memoria-cuentas-anuales-2014 -> Esta dirección nos devuelve un JSON con todas las tablas del conjunto de datos Memoria cuentas anuales: 2014.

**Comment by JJ** [comment]
Jolines, qué rápido

El 7 de mayo de 2015, 18:50, Mario Heredia <notifications@github.com>
escribió:

> Usar API de CKAN para traer los conjuntos de datos con sus tablas de Open
> Data:
>
> http://opendata.ugr.es/api/3/action/package_search?q=administracion ->
> Esta dirección nos devuelve un JSON con todos los conjuntos de datos que se
> encuentran en el grupo Administración.
>
>
> http://opendata.ugr.es/api/3/action/package_show?id=memoria-cuentas-anuales-2014
> -> Esta dirección nos devuelve un JSON con todas las tablas del conjunto de
> datos Memoria cuentas anuales: 2014.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/21>.
>



-- 
JJ

**Comment by germaaan** [comment]
Ya estaba trabajando en esto aquí: #18

**Comment by mariohm** [comment]
You rules! xD

**Comment by JJ** [comment]
Rule!!!! Ese B1...

2015-05-07 19:22 GMT+02:00 Mario Heredia <notifications@github.com>:

> You rules! xD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/21#issuecomment-99943482>
> .
>



-- 
JJ

**Comment by mariohm** [comment]
Ha sido a propósito. FIN

**Comment by germaaan** [comment]
Como está duplicado, cierro este.
