### ISSUE TITLE
Testeo de funcionamiento en otros navegadores (safari e IE)

### ISSUE THREAD

**Issue by mariohm** [oslugr/ugr-transparente-servidor#23]
Se han detectado errores de Javascript en IE v.8

**Comment by JJ** [comment]
Que le den.

2015-05-07 18:53 GMT+02:00 Mario Heredia <notifications@github.com>:

> Se han detectado errores de Javascript en IE v.8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/23>.
>



-- 
JJ
