### ISSUE TITLE
Las rutas deberían ser configurables

### ISSUE THREAD

**Issue by JJ** [oslugr/ugr-transparente-servidor#40]
Ahora mismo están ahí, a jopo, en app.js.

**Comment by demiurgosoft** [comment]
un config.json serviría?

**Comment by demiurgosoft** [comment]
Va a ser necesario modificar algunas plantillas y configuración de routes para algunas páginas

**Comment by demiurgosoft** [comment]
Faltan las siguientes rutas:
* [ ] index
* [ ] infoInstitucional
* [ ] solicitudInfo
* [ ] mapaWeb
* [ ] buscador
* [ ] calendario
* [ ] calendarioSolo
* [ ] perfil contratante
* [ ] archivos del buscador

**Comment by demiurgosoft** [comment]
mapaweb e index se dejarán como estan de momento (no se adaptan a la estructura común de las páginas)

Calendario y CalendarioSolo se dejan también pues no se usan de momento
