### ISSUE TITLE
Añadir al README varios badges informativos

### ISSUE THREAD

**Issue by germaaan** [oslugr/ugr-transparente-servidor#46]
Por lo pronto:
- [x] versión de Node
- [x] licencia
- [x] estado de integración continua en Travis
- [x] dependencias en David
- [x] cobertura de código en Coveralls

**Comment by demiurgosoft** [comment]
Dependencias en gemnasiun añadidas en un badge

**Comment by JJ** [comment]
¿eiin?

**Comment by demiurgosoft** [comment]
badge de gemnasium para analizar dependencias de npm

**Comment by JJ** [comment]
Ahm.

2016-01-28 13:22 GMT+01:00 Andrés <notifications@github.com>:

> badge de gemnasium para analizar dependencias de npm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/46#issuecomment-176153827>
> .
>



-- 
JJ
