### ISSUE TITLE
Documentar código para generar documentación automaticamente

### ISSUE THREAD

**Issue by germaaan** [oslugr/ugr-transparente-servidor#48]
La documentación se puede realizar con Docco.

**Comment by demiurgosoft** [comment]
groc mola

**Comment by JJ** [comment]
Yo he usado docco y no está mal. NO sé si estará actualizado o habrá cambiado de nombre ahora... ¿Por qué groc?

**Comment by JJ** [comment]
Parece que se puede integrar también con grunt https://github.com/jdcataldo/grunt-groc

**Comment by JJ** [comment]
Bueno, y con gulp https://www.npmjs.com/package/gulp-groc

**Comment by demiurgosoft** [comment]
groc es mas bonico, además permite jugar un poco más con que comentarios poner y cuales no, pero básicamente funciona igual que docco

**Comment by demiurgosoft** [comment]
tambien se puede integrar con gulp (https://www.npmjs.com/package/gulp-groc) y docco es demasiado mainstram

**Comment by JJ** [comment]
¡Eso lo había dicho yo ya dos comentarios más arriba!

**Comment by demiurgosoft** [comment]
Ups, pense que hablabas de docco, fallo mío

**Comment by demiurgosoft** [comment]
documentacion accesible en https://oslugr.github.io/ugr-transparente-servidor/
