### ISSUE TITLE
Arreglar problemas de visualización de tablas

### ISSUE THREAD

**Issue by germaaan** [oslugr/ugr-transparente-servidor#53]
Las tablas que se realizan con la API Google Visualization en ocasiones da problemas, concretar y revisar.

**Comment by germaaan** [comment]
Solucionar problema de petición sobre HTTPS con jQuery y respuesta sobre HTTP desde CKAN, lo que hace que la respuesta sea bloqueada.

**Comment by germaaan** [comment]
efc1b2e

**Comment by germaaan** [comment]
bacf59cc462eb1a38789f2f813b7cda499a2a966

**Comment by germaaan** [comment]
En vez de usar jQuery a pelo, usar jQuery UI para hacer una presentación de los datos más amigable.

**Comment by demiurgosoft** [comment]
que falta hacer aquí? Explain!

**Comment by demiurgosoft** [comment]
podemos usar D3.js #60
