### ISSUE TITLE
Incluir enlace a solicitud general con explicación

### ISSUE THREAD

**Issue by JJ** [oslugr/ugr-transparente-servidor#6]
El enlace al formulario de solicitud general es este
https://sede.ugr.es/sede/catalogo-de-procedimientos/solicitud-generica.html?iniciar=0
Hay que incluir una explicación diciendo
* Que si eres de la UGR uses acceso identificado.
* Que si no, necesitas un certificado en el navegador (y Java y no sé cuantas cosas más)
* Que en "motivo" lo único que tienes que poner es que se hace la solicitud según la ley de transparencia

Y salvo que @nuriaricocastro diga otra cosa, ya está.

**Comment by mariohm** [comment]
Hecho, pero "invisible" hasta que Nuria me diga lo que sea. Ahora os paso en enlace para que lo veáis.

**Comment by JJ** [comment]
REcuerda cerrar el issue siempre con un commit.

2015-01-09 18:02 GMT+01:00 Mario <notifications@github.com>:

> Hecho, pero "invisible" hasta que Nuria me diga lo que sea. Ahora os paso
> en enlace para que lo veáis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/6#issuecomment-69364002>
> .
>



-- 
JJ

**Comment by mariohm** [comment]
Cuando lo ponga visible de nuevo cierro esto. También, aprovecho, y ya lo hago con un commit.

**Comment by JJ** [comment]
Ahora provisionalmente tenemos que volver a poner esto. ¿Lo puedo poner yo? ¿Dónde anda?

**Comment by germaaan** [comment]
Ahora mismo está "accesible" solo introduciendo la dirección manualmente desde [http://transparente.ugr.es/testSolicitudes.html](http://transparente.ugr.es/testSolicitudes.html) que fue el que se hizo provisionalmente, sería cambiarle la dirección y añadir el enlace al menú de la izquierda.

**Comment by JJ** [comment]
Si puedes hazlo, por favor.

El 30 de julio de 2015, 9:16, German Martinez <notifications@github.com>
escribió:

> Ahora mismo está "accesible" solo introduciendo la dirección manualmente
> desde http://transparente.ugr.es/testSolicitudes.html que fue el que se
> hizo provisionalmente, sería cambiarle la dirección y añadir el enlace al
> menú de la izquierda.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/6#issuecomment-126207214>
> .
>



-- 
JJ

**Comment by JJ** [comment]
Um, es una página estática, no sigue la plantilla del resto, ¿no?

en fin, provisionalmente lo haremos así pero más adelante habrá que
cambiarlo

El 30 de julio de 2015, 9:44, JJ Merelo <jjmerelo@gmail.com> escribió:

> Si puedes hazlo, por favor.
>
> El 30 de julio de 2015, 9:16, German Martinez <notifications@github.com>
> escribió:
>
>> Ahora mismo está "accesible" solo introduciendo la dirección manualmente
>> desde http://transparente.ugr.es/testSolicitudes.html que fue el que se
>> hizo provisionalmente, sería cambiarle la dirección y añadir el enlace al
>> menú de la izquierda.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/oslugr/ugr-transparente-servidor/issues/6#issuecomment-126207214>
>> .
>>
>
>
>
> --
> JJ
>



-- 
JJ

**Comment by germaaan** [comment]
Sí, lo hago ahora en un momento.

**Comment by germaaan** [comment]
ca3525e8f4d68b919f2f58f371e2cc8afaf6df8a

**Comment by germaaan** [comment]
Hecho y desplegado en el servidor -> [http://transparente.ugr.es/solicitudInfo.html](http://transparente.ugr.es/solicitudInfo.html)

**Comment by JJ** [comment]
Gracias, Germán, eres un crack.

2015-07-30 14:07 GMT+02:00 German Martinez <notifications@github.com>:

> Hecho y desplegado en el servidor ->
> http://transparente.ugr.es/solicitudInfo.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/6#issuecomment-126298356>
> .
>



-- 
JJ
