### ISSUE TITLE
Refactorización o provisionamiento para trabajar con un servidor estático como `nginx`

### ISSUE THREAD

**Issue by JJ** [oslugr/ugr-transparente-servidor#67]
Para poder servir más eficientemente el contenido estático.

**Comment by germaaan** [comment]
eed07c7e6474f1115ce2eb733b339cfef9e932f5

296303776329746cd50556108f6d4d87ca61f65e

28882b535775dc9256b36a6b5af6c37581f21542

**Comment by germaaan** [comment]
9944fa9c3bf8a4205deb0c5c945cf56a3e9c5813

**Comment by germaaan** [comment]
Nginx instalado, configurado y desplegado.
