### ISSUE TITLE
Hacer tablas en .jade como un mixin separado para la reutilización

### ISSUE THREAD

**Issue by demiurgosoft** [oslugr/ugr-transparente-servidor#71]
permitir la reutilización de un template jade (vamos, la gracia de un template)

**Comment by germaaan** [comment]
De hecho, es una de las grandes faltas en vista a hacer una release "oficial".

**Comment by JJ** [comment]
Insisto que con ella o sin ella deberíais ponerlo en la web, que más
oficial que esté corriendo en transparente.ugr.es no va a haber...

2016-02-10 13:00 GMT+01:00 German Martinez <notifications@github.com>:

> De hecho, es una de las grandes faltas en vista a hacer una release
> "oficial".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/71#issuecomment-182335432>
> .
>



-- 
JJ

**Comment by germaaan** [comment]
El hacer la release te refieres?

**Comment by JJ** [comment]
Sí, y ponerlo en el blog.

2016-02-11 15:00 GMT+01:00 German Martinez <notifications@github.com>:

> El hacer la release te refieres?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/71#issuecomment-182876479>
> .
>



-- 
JJ
