### ISSUE TITLE
Menú dinámico

### ISSUE THREAD

**Issue by demiurgosoft** [oslugr/ugr-transparente-servidor#73]
En lugar de un menú distinto en cada página, mejor un único menú (por ejemplo, un mixin) que se genere dinámicamente al cargar la página

**Comment by JJ** [comment]
Eso molaría.

2016-02-12 20:31 GMT+01:00 Andrés <notifications@github.com>:

> En lugar de un menú distinto en cada página, mejor un único menú (por
> ejemplo, un mixin) que se genere dinámicamente al cargar la página
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oslugr/ugr-transparente-servidor/issues/73>.
>



-- 
JJ
